name: Go CI/CD

on:
  push:
    tags:
      - 'v*.*.*' # Sadece etiketlerde çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build binary
        run: go build -o dist/groq-client

      - name: Run Tests
        run: go test ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/groq-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
